### ISSUE TITLE
DC8 doesn't boot

### ISSUE THREAD

**Issue by draanPSP** [draanPSP/timemachine#6]
In the current state of development we should be able to boot DC8 (using the original DaX payloads and nandipls (01g, 02g) extracted using [pspdecrypt](https://github.com/John-K/pspdecrypt), just like the 3.60M33.

For some reason, it doesn't boot.

**Comment by Demonic098** [comment]
DC7 and DC8 working correctly on 1K and 2K but we still missing some files to be able to boot it on 3K

**Comment by draanPSP** [comment]
Turns out the issue was unrelated to the code; I had an error in the FAT filesystem on my Memory Stick. After format it does work indeed!
